// Script File
enum rModifiers 
{
	MDF_ALPRADIATION = 154001,
	MDF_ALPRADIATIONSICK1,
	MDF_ALPRADIATIONSICK2,
	MDF_ALPRADIATIONSICK3,
	MDF_ALPRADIATIONSICK4,
	MDF_ALPRADIATIONSICK5,
	MDF_ALPRADIATIONBLOCK,
	MDF_ALPHEADACHE,
	MDF_ANABOLIC,
	MDF_TIREDNESS,
	MDF_SLEEPING,
	MDF_DRUNKENNESS,
	MDF_IMMUNITY_INFLUENZA,
	COUNT,
}